Building DAG of jobs...
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job              count
-------------  -------
all                  1
dynamic_solve       36
solve_base           2
total               39

Select jobs to execute...

[Sat Jun  8 17:14:12 2024]
rule solve_base:
    input: resources/DE_20_1.5_base.nc
    output: resources/DE_20_1.5_base_solved.nc, resources/DE_20_1.5_base_roll_solved.nc
    jobid: 21
    reason: Missing output files: resources/DE_20_1.5_base_solved.nc
    wildcards: country=DE, buses=20, transmission_limit=1.5
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Sat Jun  8 17:14:12 2024]
rule solve_base:
    input: resources/DE_20_1.0_base.nc
    output: resources/DE_20_1.0_base_solved.nc, resources/DE_20_1.0_base_roll_solved.nc
    jobid: 2
    reason: Missing output files: resources/DE_20_1.0_base_solved.nc
    wildcards: country=DE, buses=20, transmission_limit=1.0
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Sat Jun  8 17:14:36 2024]
Error in rule solve_base:
    jobid: 2
    input: resources/DE_20_1.0_base.nc
    output: resources/DE_20_1.0_base_solved.nc, resources/DE_20_1.0_base_roll_solved.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 123:
Command 'python scripts/solve_base.py resources/DE_20_1.0_base.nc resources/DE_20_1.0_base_solved.nc 130 resources/DE_20_1.0_base_roll_solved.nc 24' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 123, in __rule_solve_base
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
[Sat Jun  8 17:14:36 2024]
Error in rule solve_base:
    jobid: 21
    input: resources/DE_20_1.5_base.nc
    output: resources/DE_20_1.5_base_solved.nc, resources/DE_20_1.5_base_roll_solved.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 123:
Command 'python scripts/solve_base.py resources/DE_20_1.5_base.nc resources/DE_20_1.5_base_solved.nc 130 resources/DE_20_1.5_base_roll_solved.nc 24' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 123, in __rule_solve_base
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake\log\2024-06-08T171411.607529.snakemake.log
