Building DAG of jobs...
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                    count
-------------------  -------
all                        1
solve_base                 2
solve_contingencies       48
total                     51

Select jobs to execute...

[Wed May 29 22:41:24 2024]
rule solve_base:
    input: resources/DE_20_1.0_base.nc
    output: resources/DE_20_1.0_base_solved.nc, resources/DE_20_1.0_base_roll_solved.nc
    jobid: 2
    reason: Missing output files: resources/DE_20_1.0_base_solved.nc
    wildcards: country=DE, buses=20, transmission_limit=1.0
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Wed May 29 22:41:24 2024]
rule solve_base:
    input: resources/DE_20_1.5_base.nc
    output: resources/DE_20_1.5_base_solved.nc, resources/DE_20_1.5_base_roll_solved.nc
    jobid: 27
    reason: Missing output files: resources/DE_20_1.5_base_solved.nc
    wildcards: country=DE, buses=20, transmission_limit=1.5
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Wed May 29 23:02:43 2024]
Error in rule solve_base:
    jobid: 27
    input: resources/DE_20_1.5_base.nc
    output: resources/DE_20_1.5_base_solved.nc, resources/DE_20_1.5_base_roll_solved.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 115:
Command 'python scripts/solve_base.py resources/DE_20_1.5_base.nc resources/DE_20_1.5_base_solved.nc 130 resources/DE_20_1.5_base_roll_solved.nc 24' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 115, in __rule_solve_base
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
[Wed May 29 23:06:30 2024]
Error in rule solve_base:
    jobid: 2
    input: resources/DE_20_1.0_base.nc
    output: resources/DE_20_1.0_base_solved.nc, resources/DE_20_1.0_base_roll_solved.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 115:
Command 'python scripts/solve_base.py resources/DE_20_1.0_base.nc resources/DE_20_1.0_base_solved.nc 130 resources/DE_20_1.0_base_roll_solved.nc 24' returned non-zero exit status 1.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 115, in __rule_solve_base
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
Terminating processes on user request, this might take some time.
Complete log: .snakemake\log\2024-05-29T224123.153294.snakemake.log
